import { Database } from 'bun:sqlite';
const db = new Database('sqlite.db');

const email = "support@zalan.web.id";
const userId = "b34beee5-72a2-479b-bf71-b434f0daae6e";
// This is the hash for "admin12345678" generated by better-auth
const validHash = "163138f1c96d9dc69fbf9a2b74f57793:3be07415f34af784d159743831e6ff4e44495be93f61ecf5d360eac394183ecaf8c67176e627b8f6a3cad14aacecb8c5c6fc2c6665975394ec93e8d0c5e7d5aa";

try {
    // Delete my previous wrong entries
    db.run("DELETE FROM account WHERE user_id = ?", [userId]);

    // Insert correct entry
    db.run(`
        INSERT INTO account (id, user_id, account_id, provider_id, password, created_at, updated_at)
        VALUES (?, ?, ?, 'credential', ?, ?, ?)
    `, [crypto.randomUUID().replace(/-/g, ''), userId, userId, validHash, Math.floor(Date.now() / 1000), Math.floor(Date.now() / 1000)]);

    // Also update password in user table (though account is primary for credential)
    db.run("UPDATE user SET password = ? WHERE id = ?", [validHash, userId]);

    console.log('Admin account fixed with correct provider_id and account_id');
} catch (e) {
    console.error(e);
}

db.close();
